#!/bin/sh
set -e
package_name=xed-gedit
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/pluma.desktop"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/pluma.desktop"
;;
esac
exit 0
